export const countries = [
  { country: "Afghanistan", code: "AF"},
  { country: "Albania", code: "AL"},
  { country: "Algeria", code: "DZ"},
  { country: "Angola", code: "AO"},
  { country: "Argentina", code: "AR"},
  { country: "Armenia", code: "AM"},
  { country: "Australia", code: "AU"},
  { country: "Austria", code: "AT"},
  { country: "Azerbaijan", code: "AZ"},
  { country: "Bahamas", code: "BS"},
  { country: "Bangladesh", code: "BD"},
  { country: "Belarus", code: "BY"},
  { country: "Belgium", code: "BE"},
  { country: "Belize", code: "BZ"},
  { country: "Benin", code: "BJ"},
  { country: "Bhutan", code: "BT"},
  { country: "Bolivia", code: "BO"},
  { country: "Bosnia and Herzegovina", code: "BA"},
  { country: "Botswana", code: "BW"},
  { country: "Brazil", code: "BR"},
  { country: "Brunei Darussalam", code: "BN"},
  { country: "Bulgaria", code: "BG"},
  { country: "Burkina Faso", code: "BF"},
  { country: "Burundi", code: "BI"},
  { country: "Cambodia", code: "KH"},
  { country: "Cameroon", code: "CM"},
  { country: "Canada", code: "CA"},
  { country: "Ivory Coast", code: "CI"},
  { country: "Central African Republic", code: "CF"},
  { country: "Chad", code: "TD"},
  { country: "Chile", code: "CL"},
  { country: "China", code: "CN"},
  { country: "Colombia", code: "CO"},
  { country: "Congo", code: "CG"},
  { country: "Democratic Republic of Congo", code: "CD"},
  { country: "Costa Rica", code: "CR"},
  { country: "Croatia", code: "HR"},
  { country: "Cuba", code: "CU"},
  { country: "Cyprus", code: "CY"},
  { country: "Czech Republic", code: "CZ"},
  { country: "Denmark", code: "DK"},
  { country: "Diamond Princess", code: "DP"},
  { country: "Djibouti", code: "DJ"},
  { country: "Dominican Republic", code: "DO"},
  { country: "DR Congo", code: "CD"},
  { country: "Ecuador", code: "EC"},
  { country: "Egypt", code: "EG"},
  { country: "El Salvador", code: "SV"},
  { country: "Equatorial Guinea", code: "GQ"},
  { country: "Eritrea", code: "ER"},
  { country: "Estonia", code: "EE"},
  { country: "Ethiopia", code: "ET"},
  { country: "Falkland Islands", code: "FK"},
  { country: "Fiji", code: "FJ"},
  { country: "Finland", code: "FI"},
  { country: "France", code: "FR"},
  { country: "French Guiana", code: "GF"},
  { country: "French Southern Territories", code: "TF"},
  { country: "Gabon", code: "GA"},
  { country: "Gambia", code: "GM"},
  { country: "Georgia", code: "GE"},
  { country: "Germany", code: "DE"},
  { country: "Ghana", code: "GH"},
  { country: "Greece", code: "GR"},
  { country: "Greenland", code: "GL"},
  { country: "Guatemala", code: "GT"},
  { country: "Guinea", code: "GN"},
  { country: "Guinea-Bissau", code: "GW"},
  { country: "Guyana", code: "GY"},
  { country: "Haiti", code: "HT"},
  { country: "Honduras", code: "HN"},
  { country: "Hong Kong", code: "HK"},
  { country: "Hungary", code: "HU"},
  { country: "Iceland", code: "IS"},
  { country: "India", code: "IN"},
  { country: "Indonesia", code: "ID"},
  { country: "Iran", code: "IR"},
  { country: "Iraq", code: "IQ"},
  { country: "Ireland", code: "IE"},
  { country: "Israel", code: "IL"},
  { country: "Italy", code: "IT"},
  { country: "Jamaica", code: "JM"},
  { country: "Japan", code: "JP"},
  { country: "Jordan", code: "JO"},
  { country: "Kazakhstan", code: "KZ"},
  { country: "Kenya", code: "KE"},
  { country: "Korea", code: "KP"},
  { country: "Kosovo", code: "XK"},
  { country: "Kuwait", code: "KW"},
  { country: "Kyrgyzstan", code: "KG"},
  { country: "Lao", code: "LA"},
  { country: "Latvia", code: "LV"},
  { country: "Lebanon", code: "LB"},
  { country: "Lesotho", code: "LS"},
  { country: "Liberia", code: "LR"},
  { country: "Libya", code: "LY"},
  { country: "Lithuania", code: "LT"},
  { country: "Luxembourg", code: "LU"},
  { country: "Macedonia", code: "MK"},
  { country: "Madagascar", code: "MG"},
  { country: "Malawi", code: "MW"},
  { country: "Malaysia", code: "MY"},
  { country: "Mali", code: "ML"},
  { country: "Mauritania", code: "MR"},
  { country: "Mexico", code: "MX"},
  { country: "Moldova", code: "MD"},
  { country: "Mongolia", code: "MN"},
  { country: "Montenegro", code: "ME"},
  { country: "Morocco", code: "MA"},
  { country: "Mozambique", code: "MZ"},
  { country: "Myanmar", code: "MM"},
  { country: "Namibia", code: "NA"},
  { country: "Nepal", code: "NP"},
  { country: "Netherlands", code: "NL"},
  { country: "New Caledonia", code: "NC"},
  { country: "New Zealand", code: "NZ"},
  { country: "Nicaragua", code: "NI"},
  { country: "Niger", code: "NE"},
  { country: "Nigeria", code: "NG"},
  { country: "North Korea", code: "KP"},
  { country: "Norway", code: "NO"},
  { country: "Oman", code: "OM"},
  { country: "Pakistan", code: "PK"},
  { country: "Palestine", code: "PS"},
  { country: "Panama", code: "PA"},
  { country: "Papua New Guinea", code: "PG"},
  { country: "Paraguay", code: "PY"},
  { country: "Peru", code: "PE"},
  { country: "Philippines", code: "PH"},
  { country: "Poland", code: "PL"},
  { country: "Portugal", code: "PT"},
  { country: "Puerto Rico", code: "PR"},
  { country: "Qatar", code: "QA"},
  { country: "Republic of Kosovo", code: "XK"},
  { country: "Romania", code: "RO"},
  { country: "Russia", code: "RU"},
  { country: "Rwanda", code: "RW"},
  { country: "Saudi Arabia", code: "SA"},
  { country: "Senegal", code: "SN"},
  { country: "Serbia", code: "RS"},
  { country: "Sierra Leone", code: "SL"},
  { country: "Singapore", code: "SG"},
  { country: "Slovakia", code: "SK"},
  { country: "Slovenia", code: "SI"},
  { country: "Solomon Islands", code: "SB"},
  { country: "Somalia", code: "SO"},
  { country: "South Africa", code: "ZA"},
  { country: "South Korea", code: "KR"},
  { country: "South Sudan", code: "SS"},
  { country: "Spain", code: "ES"},
  { country: "Sri Lanka", code: "LK"},
  { country: "Sudan", code: "SD"},
  { country: "Suriname", code: "SR"},
  { country: "Svalbard and Jan Mayen", code: "SJ"},
  { country: "Swaziland", code: "SZ"},
  { country: "Sweden", code: "SE"},
  { country: "Switzerland", code: "CH"},
  { country: "Syrian Arab Republic", code: "SY"},
  { country: "Taiwan", code: "TW"},
  { country: "Tajikistan", code: "TJ"},
  { country: "Tanzania", code: "TZ"},
  { country: "Thailand", code: "TH"},
  { country: "Timor-Leste", code: "TL"},
  { country: "Togo", code: "TG"},
  { country: "Trinidad and Tobago", code: "TT"},
  { country: "Tunisia", code: "TN"},
  { country: "Turkey", code: "TR"},
  { country: "Turkmenistan", code: "TM"},
  { country: "UAE", code: "AE"},
  { country: "Uganda", code: "UG"},
  { country: "United Kingdom", code: "GB"},
  { country: "Ukraine", code: "UA"},
  { country: "USA", code: "US"},
  { country: "Uruguay", code: "UY"},
  { country: "Uzbekistan", code: "UZ"},
  { country: "Vanuatu", code: "VU"},
  { country: "Venezuela", code: "VE"},
  { country: "Vietnam", code: "VN"},
  { country: "Western Sahara", code: "EH"},
  { country: "Yemen", code: "YE"},
  { country: "Zambia", code: "ZM"},
  { country: "Zimbabwe", code: "ZW"}
];

export const countriesDropdown = [
  { key: "AF", text: "Afghanistan", value: "AF", image: { avatar: true, src: 'https://www.countryflags.io/AF/flat/64.png' }},
  { key: "AL", text: "Albania", value: "AL", image: { avatar: true, src: 'https://www.countryflags.io/AL/flat/64.png' }},
  { key: "DZ", text: "Algeria", value: "DZ", image: { avatar: true, src: 'https://www.countryflags.io/DZ/flat/64.png' }},
  { key: "AO", text: "Angola", value: "AO", image: { avatar: true, src: 'https://www.countryflags.io/AO/flat/64.png' }},
  { key: "AR", text: "Argentina", value: "AR", image: { avatar: true, src: 'https://www.countryflags.io/AR/flat/64.png' }},
  { key: "AM", text: "Armenia", value: "AM", image: { avatar: true, src: 'https://www.countryflags.io/AM/flat/64.png' }},
  { key: "AU", text: "Australia", value: "AU", image: { avatar: true, src: 'https://www.countryflags.io/AU/flat/64.png' }},
  { key: "AT", text: "Austria", value: "AT", image: { avatar: true, src: 'https://www.countryflags.io/AT/flat/64.png' }},
  { key: "AZ", text: "Azerbaijan", value: "AZ", image: { avatar: true, src: 'https://www.countryflags.io/AZ/flat/64.png' }},
  { key: "BS", text: "Bahamas", value: "BS", image: { avatar: true, src: 'https://www.countryflags.io/BS/flat/64.png' }},
  { key: "BD", text: "Bangladesh", value: "BD", image: { avatar: true, src: 'https://www.countryflags.io/BD/flat/64.png' }},
  { key: "BY", text: "Belarus", value: "BY", image: { avatar: true, src: 'https://www.countryflags.io/BY/flat/64.png' }},
  { key: "BE", text: "Belgium", value: "BE", image: { avatar: true, src: 'https://www.countryflags.io/BE/flat/64.png' }},
  { key: "BZ", text: "Belize", value: "BZ", image: { avatar: true, src: 'https://www.countryflags.io/BZ/flat/64.png' }},
  { key: "BJ", text: "Benin", value: "BJ", image: { avatar: true, src: 'https://www.countryflags.io/BJ/flat/64.png' }},
  { key: "BT", text: "Bhutan", value: "BT", image: { avatar: true, src: 'https://www.countryflags.io/BT/flat/64.png' }},
  { key: "BO", text: "Bolivia", value: "BO", image: { avatar: true, src: 'https://www.countryflags.io/BO/flat/64.png' }},
  { key: "BA", text: "Bosnia and Herzegovina", value: "BA", image: { avatar: true, src: 'https://www.countryflags.io/BA/flat/64.png' }},
  { key: "BW", text: "Botswana", value: "BW", image: { avatar: true, src: 'https://www.countryflags.io/BW/flat/64.png' }},
  { key: "BR", text: "Brazil", value: "BR", image: { avatar: true, src: 'https://www.countryflags.io/BR/flat/64.png' }},
  { key: "BN", text: "Brunei Darussalam", value: "BN", image: { avatar: true, src: 'https://www.countryflags.io/BN/flat/64.png' }},
  { key: "BG", text: "Bulgaria", value: "BG", image: { avatar: true, src: 'https://www.countryflags.io/BG/flat/64.png' }},
  { key: "BF", text: "Burkina Faso", value: "BF", image: { avatar: true, src: 'https://www.countryflags.io/BF/flat/64.png' }},
  { key: "BI", text: "Burundi", value: "BI", image: { avatar: true, src: 'https://www.countryflags.io/BI/flat/64.png' }},
  { key: "KH", text: "Cambodia", value: "KH", image: { avatar: true, src: 'https://www.countryflags.io/KH/flat/64.png' }},
  { key: "CM", text: "Cameroon", value: "CM", image: { avatar: true, src: 'https://www.countryflags.io/CM/flat/64.png' }},
  { key: "CA", text: "Canada", value: "CA", image: { avatar: true, src: 'https://www.countryflags.io/CA/flat/64.png' }},
  { key: "CI", text: "Ivory Coast", value: "CI", image: { avatar: true, src: 'https://www.countryflags.io/CI/flat/64.png' }},
  { key: "CF", text: "Central African Republic", value: "CF", image: { avatar: true, src: 'https://www.countryflags.io/CF/flat/64.png' }},
  { key: "TD", text: "Chad", value: "TD", image: { avatar: true, src: 'https://www.countryflags.io/TD/flat/64.png' }},
  { key: "CL", text: "Chile", value: "CL", image: { avatar: true, src: 'https://www.countryflags.io/CL/flat/64.png' }},
  { key: "CN", text: "China", value: "CN", image: { avatar: true, src: 'https://www.countryflags.io/CN/flat/64.png' }},
  { key: "CO", text: "Colombia", value: "CO", image: { avatar: true, src: 'https://www.countryflags.io/CO/flat/64.png' }},
  { key: "CG", text: "Congo", value: "CG", image: { avatar: true, src: 'https://www.countryflags.io/CG/flat/64.png' }},
  { key: "CD", text: "Democratic Republic of Congo", value: "CD", image: { avatar: true, src: 'https://www.countryflags.io/CD/flat/64.png' }},
  { key: "CR", text: "Costa Rica", value: "CR", image: { avatar: true, src: 'https://www.countryflags.io/CR/flat/64.png' }},
  { key: "HR", text: "Croatia", value: "HR", image: { avatar: true, src: 'https://www.countryflags.io/HR/flat/64.png' }},
  { key: "CU", text: "Cuba", value: "CU", image: { avatar: true, src: 'https://www.countryflags.io/CU/flat/64.png' }},
  { key: "CY", text: "Cyprus", value: "CY", image: { avatar: true, src: 'https://www.countryflags.io/CY/flat/64.png' }},
  { key: "CZ", text: "Czech Republic", value: "CZ", image: { avatar: true, src: 'https://www.countryflags.io/CZ/flat/64.png' }},
  { key: "DK", text: "Denmark", value: "DK", image: { avatar: true, src: 'https://www.countryflags.io/DK/flat/64.png' }},
  { key: "DP", text: "Diamond Princess", value: "DP", image: { avatar: true, src: 'https://www.countryflags.io/DP/flat/64.png' }},
  { key: "DJ", text: "Djibouti", value: "DJ", image: { avatar: true, src: 'https://www.countryflags.io/DJ/flat/64.png' }},
  { key: "DO", text: "Dominican Republic", value: "DO", image: { avatar: true, src: 'https://www.countryflags.io/DO/flat/64.png' }},
  { key: "CDR", text: "DR Congo", value: "CD", image: { avatar: true, src: 'https://www.countryflags.io/CD/flat/64.png' }},
  { key: "EC", text: "Ecuador", value: "EC", image: { avatar: true, src: 'https://www.countryflags.io/EC/flat/64.png' }},
  { key: "EG", text: "Egypt", value: "EG", image: { avatar: true, src: 'https://www.countryflags.io/EG/flat/64.png' }},
  { key: "SV", text: "El Salvador", value: "SV", image: { avatar: true, src: 'https://www.countryflags.io/SV/flat/64.png' }},
  { key: "GQ", text: "Equatorial Guinea", value: "GQ", image: { avatar: true, src: 'https://www.countryflags.io/GQ/flat/64.png' }},
  { key: "ER", text: "Eritrea", value: "ER", image: { avatar: true, src: 'https://www.countryflags.io/ER/flat/64.png' }},
  { key: "EE", text: "Estonia", value: "EE", image: { avatar: true, src: 'https://www.countryflags.io/EE/flat/64.png' }},
  { key: "ET", text: "Ethiopia", value: "ET", image: { avatar: true, src: 'https://www.countryflags.io/ET/flat/64.png' }},
  { key: "FK", text: "Falkland Islands", value: "FK", image: { avatar: true, src: 'https://www.countryflags.io/FK/flat/64.png' }},
  { key: "FJ", text: "Fiji", value: "FJ", image: { avatar: true, src: 'https://www.countryflags.io/FJ/flat/64.png' }},
  { key: "FI", text: "Finland", value: "FI", image: { avatar: true, src: 'https://www.countryflags.io/FI/flat/64.png' }},
  { key: "FR", text: "France", value: "FR", image: { avatar: true, src: 'https://www.countryflags.io/FR/flat/64.png' }},
  { key: "GF", text: "French Guiana", value: "GF", image: { avatar: true, src: 'https://www.countryflags.io/GF/flat/64.png' }},
  { key: "TF", text: "French Southern Territories", value: "TF", image: { avatar: true, src: 'https://www.countryflags.io/TF/flat/64.png' }},
  { key: "GA", text: "Gabon", value: "GA", image: { avatar: true, src: 'https://www.countryflags.io/GA/flat/64.png' }},
  { key: "GM", text: "Gambia", value: "GM", image: { avatar: true, src: 'https://www.countryflags.io/GM/flat/64.png' }},
  { key: "GE", text: "Georgia", value: "GE", image: { avatar: true, src: 'https://www.countryflags.io/GE/flat/64.png' }},
  { key: "DE", text: "Germany", value: "DE", image: { avatar: true, src: 'https://www.countryflags.io/DE/flat/64.png' }},
  { key: "GH", text: "Ghana", value: "GH", image: { avatar: true, src: 'https://www.countryflags.io/GH/flat/64.png' }},
  { key: "GR", text: "Greece", value: "GR", image: { avatar: true, src: 'https://www.countryflags.io/GR/flat/64.png' }},
  { key: "GL", text: "Greenland", value: "GL", image: { avatar: true, src: 'https://www.countryflags.io/GL/flat/64.png' }},
  { key: "GT", text: "Guatemala", value: "GT", image: { avatar: true, src: 'https://www.countryflags.io/GT/flat/64.png' }},
  { key: "GN", text: "Guinea", value: "GN", image: { avatar: true, src: 'https://www.countryflags.io/GN/flat/64.png' }},
  { key: "GW", text: "Guinea-Bissau", value: "GW", image: { avatar: true, src: 'https://www.countryflags.io/GW/flat/64.png' }},
  { key: "GY", text: "Guyana", value: "GY", image: { avatar: true, src: 'https://www.countryflags.io/GY/flat/64.png' }},
  { key: "HT", text: "Haiti", value: "HT", image: { avatar: true, src: 'https://www.countryflags.io/HT/flat/64.png' }},
  { key: "HN", text: "Honduras", value: "HN", image: { avatar: true, src: 'https://www.countryflags.io/HN/flat/64.png' }},
  { key: "HK", text: "Hong Kong", value: "HK", image: { avatar: true, src: 'https://www.countryflags.io/HK/flat/64.png' }},
  { key: "HU", text: "Hungary", value: "HU", image: { avatar: true, src: 'https://www.countryflags.io/HU/flat/64.png' }},
  { key: "IS", text: "Iceland", value: "IS", image: { avatar: true, src: 'https://www.countryflags.io/IS/flat/64.png' }},
  { key: "IN", text: "India", value: "IN", image: { avatar: true, src: 'https://www.countryflags.io/IN/flat/64.png' }},
  { key: "ID", text: "Indonesia", value: "ID", image: { avatar: true, src: 'https://www.countryflags.io/ID/flat/64.png' }},
  { key: "IR", text: "Iran", value: "IR", image: { avatar: true, src: 'https://www.countryflags.io/IR/flat/64.png' }},
  { key: "IQ", text: "Iraq", value: "IQ", image: { avatar: true, src: 'https://www.countryflags.io/IQ/flat/64.png' }},
  { key: "IE", text: "Ireland", value: "IE", image: { avatar: true, src: 'https://www.countryflags.io/IE/flat/64.png' }},
  { key: "IL", text: "Israel", value: "IL", image: { avatar: true, src: 'https://www.countryflags.io/IL/flat/64.png' }},
  { key: "IT", text: "Italy", value: "IT", image: { avatar: true, src: 'https://www.countryflags.io/IT/flat/64.png' }},
  { key: "JM", text: "Jamaica", value: "JM", image: { avatar: true, src: 'https://www.countryflags.io/JM/flat/64.png' }},
  { key: "JP", text: "Japan", value: "JP", image: { avatar: true, src: 'https://www.countryflags.io/JP/flat/64.png' }},
  { key: "JO", text: "Jordan", value: "JO", image: { avatar: true, src: 'https://www.countryflags.io/JO/flat/64.png' }},
  { key: "KZ", text: "Kazakhstan", value: "KZ", image: { avatar: true, src: 'https://www.countryflags.io/KZ/flat/64.png' }},
  { key: "KE", text: "Kenya", value: "KE", image: { avatar: true, src: 'https://www.countryflags.io/KE/flat/64.png' }},
  { key: "KP", text: "Korea", value: "KP", image: { avatar: true, src: 'https://www.countryflags.io/KP/flat/64.png' }},
  { key: "XK", text: "Kosovo", value: "XK", image: { avatar: true, src: 'https://www.countryflags.io/XK/flat/64.png' }},
  { key: "KW", text: "Kuwait", value: "KW", image: { avatar: true, src: 'https://www.countryflags.io/KW/flat/64.png' }},
  { key: "KG", text: "Kyrgyzstan", value: "KG", image: { avatar: true, src: 'https://www.countryflags.io/KG/flat/64.png' }},
  { key: "LA", text: "Lao", value: "LA", image: { avatar: true, src: 'https://www.countryflags.io/LA/flat/64.png' }},
  { key: "LV", text: "Latvia", value: "LV", image: { avatar: true, src: 'https://www.countryflags.io/LV/flat/64.png' }},
  { key: "LB", text: "Lebanon", value: "LB", image: { avatar: true, src: 'https://www.countryflags.io/LB/flat/64.png' }},
  { key: "LS", text: "Lesotho", value: "LS", image: { avatar: true, src: 'https://www.countryflags.io/LS/flat/64.png' }},
  { key: "LR", text: "Liberia", value: "LR", image: { avatar: true, src: 'https://www.countryflags.io/LR/flat/64.png' }},
  { key: "LY", text: "Libya", value: "LY", image: { avatar: true, src: 'https://www.countryflags.io/LY/flat/64.png' }},
  { key: "LT", text: "Lithuania", value: "LT", image: { avatar: true, src: 'https://www.countryflags.io/LT/flat/64.png' }},
  { key: "LU", text: "Luxembourg", value: "LU", image: { avatar: true, src: 'https://www.countryflags.io/LU/flat/64.png' }},
  { key: "MK", text: "Macedonia", value: "MK", image: { avatar: true, src: 'https://www.countryflags.io/MK/flat/64.png' }},
  { key: "MG", text: "Madagascar", value: "MG", image: { avatar: true, src: 'https://www.countryflags.io/MG/flat/64.png' }},
  { key: "MW", text: "Malawi", value: "MW", image: { avatar: true, src: 'https://www.countryflags.io/MW/flat/64.png' }},
  { key: "MY", text: "Malaysia", value: "MY", image: { avatar: true, src: 'https://www.countryflags.io/MY/flat/64.png' }},
  { key: "ML", text: "Mali", value: "ML", image: { avatar: true, src: 'https://www.countryflags.io/ML/flat/64.png' }},
  { key: "MR", text: "Mauritania", value: "MR", image: { avatar: true, src: 'https://www.countryflags.io/MR/flat/64.png' }},
  { key: "MX", text: "Mexico", value: "MX", image: { avatar: true, src: 'https://www.countryflags.io/MX/flat/64.png' }},
  { key: "MD", text: "Moldova", value: "MD", image: { avatar: true, src: 'https://www.countryflags.io/MD/flat/64.png' }},
  { key: "MN", text: "Mongolia", value: "MN", image: { avatar: true, src: 'https://www.countryflags.io/MN/flat/64.png' }},
  { key: "ME", text: "Montenegro", value: "ME", image: { avatar: true, src: 'https://www.countryflags.io/ME/flat/64.png' }},
  { key: "MA", text: "Morocco", value: "MA", image: { avatar: true, src: 'https://www.countryflags.io/MA/flat/64.png' }},
  { key: "MZ", text: "Mozambique", value: "MZ", image: { avatar: true, src: 'https://www.countryflags.io/MZ/flat/64.png' }},
  { key: "MM", text: "Myanmar", value: "MM", image: { avatar: true, src: 'https://www.countryflags.io/MM/flat/64.png' }},
  { key: "NA", text: "Namibia", value: "NA", image: { avatar: true, src: 'https://www.countryflags.io/NA/flat/64.png' }},
  { key: "NP", text: "Nepal", value: "NP", image: { avatar: true, src: 'https://www.countryflags.io/NP/flat/64.png' }},
  { key: "NL", text: "Netherlands", value: "NL", image: { avatar: true, src: 'https://www.countryflags.io/NL/flat/64.png' }},
  { key: "NC", text: "New Caledonia", value: "NC", image: { avatar: true, src: 'https://www.countryflags.io/NC/flat/64.png' }},
  { key: "NZ", text: "New Zealand", value: "NZ", image: { avatar: true, src: 'https://www.countryflags.io/NZ/flat/64.png' }},
  { key: "NI", text: "Nicaragua", value: "NI", image: { avatar: true, src: 'https://www.countryflags.io/NI/flat/64.png' }},
  { key: "NE", text: "Niger", value: "NE", image: { avatar: true, src: 'https://www.countryflags.io/NE/flat/64.png' }},
  { key: "NG", text: "Nigeria", value: "NG", image: { avatar: true, src: 'https://www.countryflags.io/NG/flat/64.png' }},
  { key: "NKP", text: "North Korea", value: "KP", image: { avatar: true, src: 'https://www.countryflags.io/KP/flat/64.png' }},
  { key: "NO", text: "Norway", value: "NO", image: { avatar: true, src: 'https://www.countryflags.io/NO/flat/64.png' }},
  { key: "OM", text: "Oman", value: "OM", image: { avatar: true, src: 'https://www.countryflags.io/OM/flat/64.png' }},
  { key: "PK", text: "Pakistan", value: "PK", image: { avatar: true, src: 'https://www.countryflags.io/PK/flat/64.png' }},
  { key: "PS", text: "Palestine", value: "PS", image: { avatar: true, src: 'https://www.countryflags.io/PS/flat/64.png' }},
  { key: "PA", text: "Panama", value: "PA", image: { avatar: true, src: 'https://www.countryflags.io/PA/flat/64.png' }},
  { key: "PG", text: "Papua New Guinea", value: "PG", image: { avatar: true, src: 'https://www.countryflags.io/PG/flat/64.png' }},
  { key: "PY", text: "Paraguay", value: "PY", image: { avatar: true, src: 'https://www.countryflags.io/PY/flat/64.png' }},
  { key: "PE", text: "Peru", value: "PE", image: { avatar: true, src: 'https://www.countryflags.io/PE/flat/64.png' }},
  { key: "PH", text: "Philippines", value: "PH", image: { avatar: true, src: 'https://www.countryflags.io/PH/flat/64.png' }},
  { key: "PL", text: "Poland", value: "PL", image: { avatar: true, src: 'https://www.countryflags.io/PL/flat/64.png' }},
  { key: "PT", text: "Portugal", value: "PT", image: { avatar: true, src: 'https://www.countryflags.io/PT/flat/64.png' }},
  { key: "PR", text: "Puerto Rico", value: "PR", image: { avatar: true, src: 'https://www.countryflags.io/PR/flat/64.png' }},
  { key: "QA", text: "Qatar", value: "QA", image: { avatar: true, src: 'https://www.countryflags.io/QA/flat/64.png' }},
  { key: "RXK", text: "Republic of Kosovo", value: "XK", image: { avatar: true, src: 'https://www.countryflags.io/XK/flat/64.png' }},
  { key: "RO", text: "Romania", value: "RO", image: { avatar: true, src: 'https://www.countryflags.io/RO/flat/64.png' }},
  { key: "RU", text: "Russia", value: "RU", image: { avatar: true, src: 'https://www.countryflags.io/RU/flat/64.png' }},
  { key: "RW", text: "Rwanda", value: "RW", image: { avatar: true, src: 'https://www.countryflags.io/RW/flat/64.png' }},
  { key: "SA", text: "Saudi Arabia", value: "SA", image: { avatar: true, src: 'https://www.countryflags.io/SA/flat/64.png' }},
  { key: "SN", text: "Senegal", value: "SN", image: { avatar: true, src: 'https://www.countryflags.io/SN/flat/64.png' }},
  { key: "RS", text: "Serbia", value: "RS", image: { avatar: true, src: 'https://www.countryflags.io/RS/flat/64.png' }},
  { key: "SL", text: "Sierra Leone", value: "SL", image: { avatar: true, src: 'https://www.countryflags.io/SL/flat/64.png' }},
  { key: "SG", text: "Singapore", value: "SG", image: { avatar: true, src: 'https://www.countryflags.io/SG/flat/64.png' }},
  { key: "SK", text: "Slovakia", value: "SK", image: { avatar: true, src: 'https://www.countryflags.io/SK/flat/64.png' }},
  { key: "SI", text: "Slovenia", value: "SI", image: { avatar: true, src: 'https://www.countryflags.io/SI/flat/64.png' }},
  { key: "SB", text: "Solomon Islands", value: "SB", image: { avatar: true, src: 'https://www.countryflags.io/SB/flat/64.png' }},
  { key: "SO", text: "Somalia", value: "SO", image: { avatar: true, src: 'https://www.countryflags.io/SO/flat/64.png' }},
  { key: "ZA", text: "South Africa", value: "ZA", image: { avatar: true, src: 'https://www.countryflags.io/ZA/flat/64.png' }},
  { key: "KR", text: "South Korea", value: "KR", image: { avatar: true, src: 'https://www.countryflags.io/KR/flat/64.png' }},
  { key: "SS", text: "South Sudan", value: "SS", image: { avatar: true, src: 'https://www.countryflags.io/SS/flat/64.png' }},
  { key: "ES", text: "Spain", value: "ES", image: { avatar: true, src: 'https://www.countryflags.io/ES/flat/64.png' }},
  { key: "LK", text: "Sri Lanka", value: "LK", image: { avatar: true, src: 'https://www.countryflags.io/LK/flat/64.png' }},
  { key: "SD", text: "Sudan", value: "SD", image: { avatar: true, src: 'https://www.countryflags.io/SD/flat/64.png' }},
  { key: "SR", text: "Suriname", value: "SR", image: { avatar: true, src: 'https://www.countryflags.io/SR/flat/64.png' }},
  { key: "SJ", text: "Svalbard and Jan Mayen", value: "SJ", image: { avatar: true, src: 'https://www.countryflags.io/SJ/flat/64.png' }},
  { key: "SZ", text: "Swaziland", value: "SZ", image: { avatar: true, src: 'https://www.countryflags.io/SZ/flat/64.png' }},
  { key: "SE", text: "Sweden", value: "SE", image: { avatar: true, src: 'https://www.countryflags.io/SE/flat/64.png' }},
  { key: "CH", text: "Switzerland", value: "CH", image: { avatar: true, src: 'https://www.countryflags.io/CH/flat/64.png' }},
  { key: "SY", text: "Syrian Arab Republic", value: "SY", image: { avatar: true, src: 'https://www.countryflags.io/SY/flat/64.png' }},
  { key: "TW", text: "Taiwan", value: "TW", image: { avatar: true, src: 'https://www.countryflags.io/TW/flat/64.png' }},
  { key: "TJ", text: "Tajikistan", value: "TJ", image: { avatar: true, src: 'https://www.countryflags.io/TJ/flat/64.png' }},
  { key: "TZ", text: "Tanzania", value: "TZ", image: { avatar: true, src: 'https://www.countryflags.io/TZ/flat/64.png' }},
  { key: "TH", text: "Thailand", value: "TH", image: { avatar: true, src: 'https://www.countryflags.io/TH/flat/64.png' }},
  { key: "TL", text: "Timor-Leste", value: "TL", image: { avatar: true, src: 'https://www.countryflags.io/TL/flat/64.png' }},
  { key: "TG", text: "Togo", value: "TG", image: { avatar: true, src: 'https://www.countryflags.io/TG/flat/64.png' }},
  { key: "TT", text: "Trinidad and Tobago", value: "TT", image: { avatar: true, src: 'https://www.countryflags.io/TT/flat/64.png' }},
  { key: "TN", text: "Tunisia", value: "TN", image: { avatar: true, src: 'https://www.countryflags.io/TN/flat/64.png' }},
  { key: "TR", text: "Turkey", value: "TR", image: { avatar: true, src: 'https://www.countryflags.io/TR/flat/64.png' }},
  { key: "TM", text: "Turkmenistan", value: "TM", image: { avatar: true, src: 'https://www.countryflags.io/TM/flat/64.png' }},
  { key: "AE", text: "UAE", value: "AE", image: { avatar: true, src: 'https://www.countryflags.io/AE/flat/64.png' }},
  { key: "UG", text: "Uganda", value: "UG", image: { avatar: true, src: 'https://www.countryflags.io/UG/flat/64.png' }},
  { key: "GB", text: "United Kingdom", value: "GB", image: { avatar: true, src: 'https://www.countryflags.io/GB/flat/64.png' }},
  { key: "UA", text: "Ukraine", value: "UA", image: { avatar: true, src: 'https://www.countryflags.io/UA/flat/64.png' }},
  { key: "US", text: "USA", value: "US", image: { avatar: true, src: 'https://www.countryflags.io/US/flat/64.png' }},
  { key: "UY", text: "Uruguay", value: "UY", image: { avatar: true, src: 'https://www.countryflags.io/UY/flat/64.png' }},
  { key: "UZ", text: "Uzbekistan", value: "UZ", image: { avatar: true, src: 'https://www.countryflags.io/UZ/flat/64.png' }},
  { key: "VU", text: "Vanuatu", value: "VU", image: { avatar: true, src: 'https://www.countryflags.io/VU/flat/64.png' }},
  { key: "VE", text: "Venezuela", value: "VE", image: { avatar: true, src: 'https://www.countryflags.io/VE/flat/64.png' }},
  { key: "VN", text: "Vietnam", value: "VN", image: { avatar: true, src: 'https://www.countryflags.io/VN/flat/64.png' }},
  { key: "EH", text: "Western Sahara", value: "EH", image: { avatar: true, src: 'https://www.countryflags.io/EH/flat/64.png' }},
  { key: "YE", text: "Yemen", value: "YE", image: { avatar: true, src: 'https://www.countryflags.io/YE/flat/64.png' }},
  { key: "ZM", text: "Zambia", value: "ZM", image: { avatar: true, src: 'https://www.countryflags.io/ZM/flat/64.png' }},
  { key: "ZW", text: "Zimbabwe", value: "ZW", image: { avatar: true, src: 'https://www.countryflags.io/ZW/flat/64.png' }},
];
